# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datumtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=50)),
                ('doccount', models.IntegerField(default=0)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PostNameNum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_number', models.IntegerField()),
                ('post_name', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('street', models.CharField(default='', max_length=80)),
                ('post_name', models.CharField(default=None, max_length=80)),
                ('post_number', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='docid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Docs'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sentto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Recipients'),
        ),
        migrations.AddField(
            model_name='activity',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
