# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='post_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='post_number',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
