# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20160731_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='post_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
