# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0003_auto_20160731_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docfile', models.FileField(upload_to='')),
                ('docname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Docs')),
                ('docuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
