# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_uploadeddocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocs',
            name='docname',
            field=models.CharField(max_length=50),
        ),
    ]
