# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20160820_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocs',
            name='doctime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 20, 17, 13, 46, 952525, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
