# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import frontend.misc_functions


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_uploadeddocs_doctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocs',
            name='docfile',
            field=models.FileField(upload_to='', validators=[frontend.misc_functions.validate_file_extension]),
        ),
    ]
