# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20160820_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'List of documents'},
        ),
        migrations.AlterModelOptions(
            name='uploadeddocs',
            options={'verbose_name': 'Uploaded document', 'verbose_name_plural': 'Uploaded documents'},
        ),
        migrations.AddField(
            model_name='recipients',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
