# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20160821_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='recipients',
            options={'verbose_name': 'Recipient', 'verbose_name_plural': 'Recipients'},
        ),
        migrations.AlterField(
            model_name='recipients',
            name='email',
            field=models.EmailField(max_length=80),
        ),
    ]
