# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 16:45
from __future__ import unicode_literals

from django.db import migrations
import oauth2client.contrib.django_orm


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20160821_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostNameNum',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='credentials',
            field=oauth2client.contrib.django_orm.CredentialsField(null=True),
        ),
    ]
