# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_orm


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('frontend', '0010_auto_20160911_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credentials', oauth2client.contrib.django_orm.CredentialsField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='credentials',
        ),
    ]
